# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-25 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0002_auto_20180525_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='image_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='image_path',
            field=models.ImageField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
