# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-25 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0003_auto_20180525_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='image_path',
            field=models.ImageField(default='home/next/Desktop/no-data.jpg', upload_to='home/next/Desktop/'),
        ),
    ]
