# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-25 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0005_auto_20180525_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='image_path',
            field=models.ImageField(blank=True, default='no-data.jpg', null=True, upload_to=''),
        ),
    ]
