# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-28 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0006_auto_20180525_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='area',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='route',
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_area_id', to='configure.AreaDetails'),
        ),
    ]
